### ISSUE TITLE
Git LFS is disabled for this repository

### ISSUE THREAD

**Issue by noble6emc2** [iesl/stance#1]
Hi guys, I've cloned the repository successfully. But when I do `git lfs pull` ,  it throws `batch response: Git LFS is disabled for this repository.
error: failed to fetch some objects from 'https://github.com/iesl/stance.git/info/lfs'`, which indicates that LFS is disabled in this repository.

Best regards,
    Jerry

**Comment by dptam** [comment]
Hi Jerry, 

Sorry about that. We changed the data so that it is now stored at a google drive link.

**Comment by dptam** [comment]
Hi Jerry,

Sorry about that. We changed the data so that it is now stored at a google drive link.
